---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ap-northeast-1
  version: "1.19"

availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:ap-northeast-1:883753100711:key/e73fe5e1-ec60-4e30-b457-ab8ef09e09ec
